### ISSUE TITLE
make preview-all failing

### ISSUE THREAD

**Issue by wadebee** [validatedpatterns/multicloud-gitops#348]
Cloning latest repo and running `make preview-all ` fails with:

[multicloud-gitops]$ make preview-all
make -f common/Makefile preview-all
make[1]: Entering directory '/home/user/repos/GitHub/validatedpatterns/multicloud-gitops'
Error: open /home/user/repos/GitHub/validatedpatterns/multicloud-gitops/overrides/values-Azure.yaml: no such file or directory
Error: open /home/user/repos/GitHub/validatedpatterns/multicloud-gitops/overrides/values-Azure.yaml: no such file or directory
Error: open /home/user/repos/GitHub/validatedpatterns/multicloud-gitops/overrides/values-Azure.yaml: no such file or directory
Error: open /home/user/repos/GitHub/validatedpatterns/multicloud-gitops/overrides/values-Azure.yaml: no such file or directory
Error: open /home/user/repos/GitHub/validatedpatterns/multicloud-gitops/overrides/values-Azure.yaml: no such file or directory
common/scripts/preview.sh: eval: line 79: unexpected EOF while looking for matching `"'
common/scripts/preview.sh: eval: line 80: syntax error: unexpected end of file
common/scripts/preview.sh: eval: line 79: unexpected EOF while looking for matching `"'
common/scripts/preview.sh: eval: line 80: syntax error: unexpected end of file
common/scripts/preview.sh: eval: line 79: unexpected EOF while looking for matching `"'
common/scripts/preview.sh: eval: line 80: syntax error: unexpected end of file
make[1]: *** [common/Makefile:59: preview-all] Error 2
make[1]: Leaving directory '/home/user/repos/GitHub/validatedpatterns/multicloud-gitops'
make: *** [Makefile:12: preview-all] Error 2

**Comment by claudiol** [comment]
Hi @wadebee 
   try running it using out utility container like so
`./pattern.sh make preview-all`
I am seeing the looking at the last error in the script.  It's a bit cryptic but I will look into it.

Best,
Lester

**Comment by claudiol** [comment]
Hi @wadebee 
   So the issue with the error `common/scripts/preview.sh: eval: line 80: syntax error: unexpected end of file` has to do with the comments in the **sharedValueFiles:** section of values-hub.yaml and values-group-one.yaml files.

Here's a sample output from my laptop once I remove the comments in that section:
```
claudiol@fedora:multicloud-gitops (main *$%|u= origin/main)
$ ./pattern.sh make preview-all
make -f common/Makefile preview-all
make[1]: Entering directory '/home/claudiol/work/gitrepos/multicloud-gitops'
helm template common/acm --name-template acm -n open-cluster-management  -f /home/claudiol/work/gitrepos/multicloud-gitops/overrides/values-AWS.yaml   --set global.pattern=multicloud-gitops --set global.repoURL=https://github.com/claudiol/multicloud-gitops.git --set main.git.repoURL=https://github.com/claudiol/multicloud-gitops.git --set main.git.revision=main --set global.namespace=open-cluster-management --set global.hubClusterDomain=apps.lc-claudiol-dillon-6c0f-1.blueprints.rhecoeng.com --set global.localClusterDomain=apps.lc-claudiol-dillon-6c0f-1.blueprints.rhecoeng.com --set global.clusterDomain=lc-claudiol-dillon-6c0f-1.blueprints.rhecoeng.com --set global.clusterVersion=4.14 --set global.clusterPlatform=AWS
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/claudiol/work/clusters/us-west-1-claudiol-dillon-6c0f-1/auth/kubeconfig
---
# Source: acm/templates/policies/acm-hub-ca-policy.yaml
# This pushes out the HUB's Certificate Authorities on to the imported clusters
---
# Source: acm/templates/policies/application-policies.yaml
# TODO: Also create a GitOpsCluster.apps.open-cluster-management.io
---
# Source: acm/templates/policies/private-repo-policies.yaml
# We copy the vp-private-repo-credentials from the "openshift-gitops" namespace
# to the "open-cluster-management" via the "private-hub-policy"
#
# Then we copy the secret from the "open-cluster-management" namespace to the
# managed clusters "openshift-gitops" instance
#
# And we also copy the same secret to the namespaced argo's namespace
---
# Source: acm/templates/multiclusterhub.yaml
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    installer.open-cluster-management.io/mce-subscription-spec: '{"source": "redhat-operators" }'
spec: {}
---
<SNIP for brevity>
# Source: hello-world/templates/hello-world-route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: hello-world
    weight: 100
  wildcardPolicy: None
make[1]: Leaving directory '/home/claudiol/work/gitrepos/multicloud-gitops'
```
Let me know if this helps.

Best,
Lester

**Comment by wadebee** [comment]
Hi Claudio - I wasn't aware of the need for pattern.sh so thanks for that. 

Is its use documented anywhere? I ask because we have a company TLS CA that is needed and I am getting TLS cert errors that I don't know how to resolve:
 
./pattern.sh make preview-all
make -f common/Makefile preview-all
make[1]: Entering directory '/home/user/repos/EnterpriseKubernetes/multicloud-gitops'
E0322 18:46:08.601821      37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority
E0322 18:46:13.728943      37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority
E0322 18:46:18.864424      37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority
E0322 18:46:23.998418      37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority
^Cmake[1]: *** [common/Makefile:59: preview-all] Interrupt
make: *** [Makefile:12: preview-all] Interrupt
make: *** wait: No child processes.  Stop.

**Comment by claudiol** [comment]
Hi @wadebee 
   Ok so the utility-container definition lives here: https://github.com/validatedpatterns/utility-container

I have never seen this before. Perhaps it's the `oc` cli that is failing?  I think that if you look under **common/scripts/preview.sh** you will see that the calls to `oc` are probably failing.  

It should be using your `kubeconfig`  but I'm not sure how your environment is set up.  If you want send me an email at claudiol@redhat.com and maybe we can get on a zoom or gmeet to discuss.

Best,
Lester

**Comment by mbaldessari** [comment]
> Hi Claudio - I wasn't aware of the need for pattern.sh so thanks for that.
> 
> Is its use documented anywhere? I ask because we have a company TLS CA that is needed and I am getting TLS cert errors that I don't know how to resolve:
> 
> ./pattern.sh make preview-all make -f common/Makefile preview-all make[1]: Entering directory '/home/user/repos/EnterpriseKubernetes/multicloud-gitops' E0322 18:46:08.601821 37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority E0322 18:46:13.728943 37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority E0322 18:46:18.864424 37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority E0322 18:46:23.998418 37 memcache.go:238] couldn't get current server API group list: Get "https://api.mycluster.aroapp.azure.us:6443/api?timeout=32s": x509: certificate signed by unknown authority ^Cmake[1]: *** [common/Makefile:59: preview-all] Interrupt make: *** [Makefile:12: preview-all] Interrupt make: *** wait: No child processes. Stop.

Hi Wade, 

the custom PKI is an interesting case that we never thought of. Could you try the following patch (assuming your custom CA is installed system-wide under /etc/pki):
```
diff --git a/common/scripts/pattern-util.sh b/common/scripts/pattern-util.sh
index 9cec19fa..ea02b7ef 100755
--- a/common/scripts/pattern-util.sh
+++ b/common/scripts/pattern-util.sh
@@ -56,6 +56,7 @@ podman run -it --rm --pull=newer \
        --security-opt label=disable \
        -e EXTRA_HELM_OPTS \
        -e KUBECONFIG \
+       -v /etc/pki:/etc/pki:ro \
        -v "${HOME}":"${HOME}" \
        -v "${HOME}":/pattern-home \
        ${PODMAN_ARGS} \
```

and report back if that fixes the `x509: certificate signed by unknown authority` errors? I suspect this is entirely orthogonal to the preview-all target failing, which we'll look into

**Comment by wadebee** [comment]
Thank you @mbaldessari and @claudiol for the helpful pointers. I have been able to get this working now. This "client-side validation tool" should help speed up the inner loop of my config/override dev process.

A couple points of feedback:
- Since I am using a Fedora based client to run VP - adding a mount to /etc/pki corrected my TLS issue.  I image non-Fedora users might need a different path like /usr/local/share/ca-certificates/.
- I needed to remove 1 line from values-hub.yaml to get output. It was the - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml' that appears to be a default from your upstream repo. Could you either remove that line from upstream or provide default values for each major platform (Azure/AWS) so that this setting works by default?
- I was surprised that I need to be logged into a cluster for the make preview parsing to work. Since this is (I believe) supposed to be a client-side parsing engine, why is there a need to be connected to a remote? The forced connection appears to be coming from these 3 lines of common/preview.sh

  ```
  platform=$(oc get Infrastructure.config.openshift.io/cluster  -o jsonpath='{.spec.platformSpec.type}')
  ocpversion=$(oc get clusterversion/version -o jsonpath='{.status.desired.version}' | awk -F. '{print $1"."$2}')
  domain=$(oc get Ingress.config.openshift.io/cluster -o jsonpath='{.spec.domain}' | sed 's/^apps.//')
  ```   

  Could these be converted to local variables by default with a dynamic runtime override? This would allow for better automated testing.

Thanks again for the fast help with this. 

Maybe with a little extra VP doc about the need for a pattern.sh launch of `make preview-all` - this issue can be closed?

**Comment by mbaldessari** [comment]
FWIW I merged https://github.com/validatedpatterns/common/pull/444 to fix the pki issue you saw (thanks again for bringing that up)
