### ISSUE TITLE
Vault-unseal CronJob

### ISSUE THREAD

**Issue by wadebee** [validatedpatterns/multicloud-gitops#349]
Somewhere in the last few months of VP commits a change was made that creates a Vault unseal CronJob in the imperative namespace by default. Since we do not use vault, this job perpetually fails.

Is there a switch to turn off this behavior?  

The resource itself seems to be defined at common/clustergroup/templates/imperative/unsealjob.yaml 

There is a toggle on line 1 that looks promising:
`{{- if eq .Values.global.secretStore.backend "vault" | default "vault" }}`

But looking at common/clustergroup/values.schema.json it does not seem to support a backend parameter:

```
    "SecretStore": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the external secret backend",
          "default": "vault-backend"
        },
        "kind": {
          "type": "string",
          "description": "Type of the external secret backend",
          "default": "ClusterSecretStore"
        }
      },
      "required": [
        "name",
        "kind"
      ],
      "title": "SecretsStore"
    },
```

Should the unseal job toggle be:
 `{{- if eq .Values.global.secretStore.kind "vault-backend" | default "vault-backend" }}`

So that end users could turn off this behavior with a change to values-global.yaml:
```
---
global:
  pattern: multicloud-gitops
  secretStore:
    kind: <something-else-here>
```

**Comment by claudiol** [comment]
Hi @wadebee,
   Right ... Let me quickly check because I did run into this and I had a patch that never made it to turn that off.  But I can probably have you patch it and then we will try to remedy the issue on our side.

Best,
Lester

**Comment by mbaldessari** [comment]
We should probably revive https://github.com/validatedpatterns/multicloud-gitops/issues/349

**Comment by mbaldessari** [comment]
One day I will learn how to copy and paste. Here is the proper link https://github.com/validatedpatterns/common/pull/409

**Comment by wadebee** [comment]
Let me know how you wish to handle. 

I can close this and reopen https://github.com/validatedpatterns/common/pull/409 or we can work off this new issue. 

Looking at #409 - it does appear to be the same ask.

**Comment by mbaldessari** [comment]
I think at this point we want to fix the schema and that should be enough? https://github.com/validatedpatterns/common/pull/451 should be sufficient?

**Comment by wadebee** [comment]
I am not yet able to get this working in the way I expected. I updated my values.schema.json to match your common#451 commit and then added the following to my values-global.yaml in root of project.

```
---
global:
  pattern: multicloud-gitops
  secretStore:
    backend: kubernetes
```

I expected my override of secretStore backend to a non-vault value would prevent any of the imperative vault-unseal logic to run. But it still does.

Further - I am reviewing my `. pattern make preview-all ` output trying to troubleshoot this values-global override logic. However, I am not seeing any of the imperative resource definitions in this output. (eg: no cronjob). 

Shouldn't I be seeing all resource creation from preview-all?

**Comment by mbaldessari** [comment]
Thanks @wadebee , color me surprised: helm has certainly a rather odd way of treating the default which is what is tripping us up here (I suspect this is some form of https://www.github.com/helm/helm/issues/3308). @mhjacks CCing you purely for info as this was quite surprising to me.

I'll grep for the whole codebase around this and see that we come up with a proper fix. For now I am thinking I will go with:
```
--- a/common/clustergroup/templates/imperative/unsealjob.yaml
+++ b/common/clustergroup/templates/imperative/unsealjob.yaml
@@ -1,4 +1,4 @@
-{{- if eq .Values.global.secretStore.backend "vault" | default "vault" }}
+{{- if or (eq .Values.global.secretStore.backend "vault") (not (hasKey .Values.global.secretStore "backend")) }}
 {{- if not (eq .Values.enabled "plumbing") }}
 {{- if $.Values.clusterGroup.isHubCluster }}
 ---
```
Am just looking around to see if there is a less obnoxious syntax. 

I'll also open a separate issue to track preview-all.sh not rendering the "entry point" of a pattern (i.e. the common/clustergroup chart).

**Comment by mbaldessari** [comment]
https://github.com/validatedpatterns/common/issues/452 is the issue for the preview missing clusterGroup (and the overrides for the three lookups, so we do not forget that part)

**Comment by mbaldessari** [comment]
So I merged https://github.com/validatedpatterns/common/pull/451 which I believe should fix this unseal once and for all (thanks for your patience here). Let me know if we can close this or if it needs some more work

**Comment by wadebee** [comment]
Just ran a fresh hub cluster install and no more vault-unseal cronjob! :)

Nice work - thanks!
